spring.application.name=ai-game-programming-mqtt

# Mqtt
mqtt.host=test.mosquitto.org
mqtt.port=1883

# Compo 1 to launch one then the other
mqtt.user=Colin
mqtt.opponent=Jake

# Compo 2 to launch one then the other
# mqtt.user=Jake
# mqtt.opponent=Colin

# Command
command=python test.py
